### ISSUE TITLE
Recording local video on ios

### ISSUE THREAD

**Issue by swift2geek** [twilio/video-quickstart-ios#225]
Hi,
we are currently trying to record local video tracks (TVILocalVideoTrack), but i guess there are some missing methods.

```
...
var localVideoTrack: TVILocalVideoTrack?
...

    func startRec() {
        let documentsURL = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
        let filepath = documentsURL.appendingPathComponent("temp2")
        var recordingDelegate:AVCaptureFileOutputRecordingDelegate? = self

        videoFileOutput = AVCaptureMovieFileOutput()
      
        self.captureSession?.addOutput(videoFileOutput!)


        videoFileOutput?.startRecording(to: filepath, recordingDelegate: recordingDelegate!)
    }
```

when i try to addOutput to localVideoTrack i got an error. 
We also found similar problem #https://github.com/twilio/video-quickstart-swift/issues/123
but its kindly different.

Any help will be appreciated.

**Comment by ceaglest** [comment]
Hi @swift2geek,

You can add a TVIVideoRenderer to TVILocalVideoTrack using `addRenderer:` for the purposes of recording. This interface is fairly generic and not related to AVCaptureSession APIs offered by Apple.

There is some excellent information in https://github.com/twilio/video-quickstart-swift/issues/123 looking at recording remote video Tracks using AVAssetWriter.

I also provided a code snippet which demonstrates using TVIVideoRenderer to record still frames from a TVILocalVideoTrack in https://github.com/twilio/video-quickstart-swift/issues/142.

Hopefully this is helpful to you, but I can provide more info if needed. I also have some WIP code for Video Track recording here: https://github.com/ceaglest/video-quickstart-swift/blob/task/renderer-example/VideoRendererExample/VideoRenderers/ExampleVideoRecorder.swift

Best,
Chris

**Comment by ceaglest** [comment]
Hey @swift2geek,

Were you able to get recording up and running? Is there anything else I can help with?

Best,
Chris

**Comment by TheBottleSeller** [comment]
Hi @ceaglest , were you able to finish up that sample code for saving a local-full res video from the camera that is also streamed to Twilio room (with all the bandwidth adjustments) [here](https://github.com/ceaglest/video-quickstart-swift/blob/task/renderer-example/VideoRendererExample/VideoRenderers/ExampleVideoRecorder.swift)

I have been trying to do this and have been hitting a lot of issues... is the general approach that I will need to to use `renderFrame` to write to an `AVAssetWriter` to stitch together frames into a local video? Will these frames be as high quality as they can be (i.e. not reduced in quality to handle bandwidth contraints)?

Thank you for any help!

**Comment by ceaglest** [comment]
Hi @TheBottleSeller,

> were you able to finish up that sample code for saving a local-full res video from the camera that is also streamed to Twilio room (with all the bandwidth adjustments) here

I'm sorry to say that I have not. This is still something we want to do, and I haven't forgot about the open sample code PRs that are in need of more work.

> is the general approach that I will need to to use renderFrame to write to an AVAssetWriter to stitch together frames into a local video? Will these frames be as high quality as they can be (i.e. not reduced in quality to handle bandwidth contraints)?

Yes, I would recommend attaching a renderer to the `TVILocalVideoTrack` in order to record the contents of a `TVICameraSource` or `TVICameraCapturer`. The frames delivered to `renderFrame` will be in the original quality and format, assuming that your renderer opts into support for the pixel format (NV12 / 420f / kCVPixelFormatType_420YpCbCr8BiPlanarFullRange). The only caveat here, is that the timestamps have already been translated (to compensate for differences between the Camera's clock and NTP). Offering the original timestamps (such as for recording purposes), could be an improvement to make with our APIs. If you can suffer a small amount of translation of timestamps then I think this approach is doable.

Sorry that I can't just show you working code here, but I hope this is at least helpful.

Best,
Chris

**Comment by ceaglest** [comment]
Hi @TheBottleSeller,

It looks like you are pretty close. A few things that stand out to me:

1. The duration is incorrect. I'm not sure what the absolute best way to compute this is when there is timestamp remapping happening. You could estimate based upon the delta with the previous timestamp or based upon the frame rate that is being captured.
2. `CVBytesPerRow` is 0. This seems slightly odd to me, but I wouldn't argue with `CMVideoFormatDescriptionCreateForImageBuffer`. Just a thought.

Best,
Chris

**Comment by TheBottleSeller** [comment]
Thank you @ceaglest , so I have tried

1) setting the duration to 1/30 seconds and setting the presentation timestamp to be zero'ed from the first frame (`recorderTimestamp` is the timestamp of the first frame)
```
        let frameTimestamp = CMTimeMake(value: frame.timestamp.value - recorderTimestamp.value, timescale: frame.timestamp.timescale)
        var sampleTiming = CMSampleTimingInfo.init(
            duration: CMTimeMake(value: 1, timescale: Int32(self.frameRate)),
            presentationTimeStamp: frameTimestamp,
            decodeTimeStamp: CMTime.invalid
        )
```
2. Unsure what to do with `CVBytesPerRow = 0`. I agree, it seems odd but I cannot find any reference to what might be happening here.
3. I am now using the video codec: `AVVideoCodecType.jpeg`

Currently the failure is still happening from the very first frame (same as above).

Thanks for the help, I will keep digging. Any other ideas would be much appreciated, particularly around that `CVBytesPerRow = 0`

**Comment by ceaglest** [comment]
Hi @TheBottleSeller,

I updated my old [VideoRendererExample PR](https://github.com/twilio/video-quickstart-swift/pull/286) for Swift 4.2, and `TVIVideoSource`. I was able to get video recording from the front camera working, even in the largest format available on my iPhone X (3088 x 2320). Be warned that rotation tags are not yet supported and that > HD recordings take up a lot of disk space.

The app starts recording your local camera right away. Double tapping stops recording, leaving an mp4 file in your app's documents directory. I've enabled iTunes file sharing so that you can take a quick look at the result.

I'll be out the office for the rest of the week, but @piyushtank might be able to help if you have more questions about local video recording.

Best,
Chris

**Comment by lucasalgarra** [comment]
Hi

Did this discussion continue since then? Is there currently a solution for recording the local video?

Thanks

**Comment by piyushtank** [comment]
@lucasalgarra As @ceaglest mentioned on this thread, we have [VideoRendererExample PR](https://github.com/twilio/video-quickstart-ios/pull/286) which demonstrates writing your own custom renderer. We plan to add more example quickstarts in the future but, at present, we do not have a sample app for custom video renderer, so I recommend using [VideoRendererExample PR](https://github.com/twilio/video-quickstart-ios/pull/286) as a reference to implement your used case.

Let me know if you have any questions.

**Comment by ceaglest** [comment]
I am sorry @lucasalgarra, I am kicking myself for not getting the PR merged and officially adding the VideoRendererExample. The ExampleVideoRecorder class in the PR is a good starting point, and should be fine for local video. For remote video that is VP8 or VP9 the recorder won't support the I420 pixel format. If the local video is from the camera then it will be NV12 and is supported.

We generally recommend using Group Rooms for audio/video recording since they have a rich set of APIs for [managing recordings](https://www.twilio.com/docs/video/api/recordings-resource) and [composing audio/video Tracks](https://www.twilio.com/docs/video/api/compositions-resource).

**Comment by piyushtank** [comment]
Closing an old ticket. Feel free to reopen or file another ticket if you run into any issues.
