### ISSUE TITLE
Performance optimization for connecting to the room

### ISSUE THREAD

**Issue by MilanNosal** [twilio/video-quickstart-ios#346]
Hi!
In our app, we need to make the use of the network as efficient as possible in order to keep the transmitted video of the highest possible quality. We are having quite an unusual setup, where the app connects to the room, and then a broadcast extension connects to the same room under a different identity. App is used to hold a call, extension is used to broadcast screen share. Now I expect that having two connections at the same time puts more weight on the network connection.
My question here is: do you use some kind of performance optimizations to publish/subscribe only that what is necessary? Is there some setting I can use to tell Twilio in the broadcast extension, that that connection is supposed to just publish, but we do not need to subscribe anything for that particular connection? The broadcast extension is supposed to share the screen, but it does not present anything to the extension user.
Thanks!
Best
Milan

**Comment by nickoli58** [comment]
@piyushtank Thank you. It would be really helpful if you could provide an example of how do use the encoding parameters to give strong preferential network priority to the broadcast extension. Is it just setting a high minimum? A really short example would be super helpful. Thank you for all your great work.

**Comment by nickoli58** [comment]
Specifically, maximize the quality of the broadcast video

**Comment by nickoli58** [comment]
Thank you, 

This sounds good, but could you please give me an example of what parameters I could use in order to prioritize the broadcast extension video? Any encoding parameters are use seem to have no effect. Thank you so much for your help.

**Comment by piyushtank** [comment]
@nickoli58 Unfortunately, at present, we do not have track priorities APIs available. But we are planning to add in future.

> Any encoding parameters are use seem to have no effect. 

Can you share code snippet on how you are limiting the bitrates?

**Comment by ceaglest** [comment]
Hi Developers,

The original question was about connecting to a broadcast extension without subscribing to Tracks. This has been possible since [2.10.0](https://www.twilio.com/docs/video/changelog-twilio-video-ios-version-2x#2100-april-24-2019). We have also updated RepalyKitExample to use EncodingParameters in order to constrain bandwidth usage, and updated the [MultiPartyExample](https://github.com/twilio/video-quickstart-ios/pull/411) to demonstrate how to use less bandwidth when sharing the camera.

I'm closing this ticket since the original questions have all been answered.

Best,
Chris
