### ISSUE TITLE
View Controller not de allocated because of TVILocalVideoTrack 

### ISSUE THREAD

**Issue by PrashantKT** [twilio/video-quickstart-ios#369]
I have following code

```

        self.videoTrack = TVILocalVideoTrack(source: self)

  let option = TVIConnectOptions(token: token) {[weak self] (builder) in
                guard let `self` = self else {return}
                builder.audioTracks = [self.audioTrack!]
                builder.videoTracks = [self.videoTrack!]
                builder.roomName = "test"
                builder.dataTracks = [self.localDataTrack!]
            }
```

because of  videoTrack view controller is not deallocated when I press back to pop view controller.

If I comment    `builder.videoTracks = [self.videoTrack!]` Then view controller deallocated correctly 

Please suggest

**Comment by piyushtank** [comment]
@PrashantKT The local video track has a strong reference to the source (see the [documentation](https://twilio.github.io/twilio-video-ios/docs/latest/Classes/TVILocalVideoTrack.html#//api/name/source)). When you create `TVILocalVideoTrack(source: self)`, you are passing `self` as the video source which will be held by TVILocalVideoTrack with a `strong` link to it. Because of this reference cycle between ViewController and TVILocalVideoTrack, they do not get deleted even if you press back button. 

One way to fix this is setting `self.videoTrack = nil` in `viewWillDisappear`

Let me know if you have any question.

Best,
Piyush
