### ISSUE TITLE
Removing TVI Keyword 

### ISSUE THREAD

**Issue by hardikdevios** [twilio/video-quickstart-ios#436]
### Description
Removing TVI Keyword I understand Swift Doesn't need Prefix.

#### Expected Behavior

I personally fill the ``TVI`` Keyword was easy to identify for the Bug and debugging and also for Code assistant as in My Application I already have ``VideoView`` ``RemoteParticipant`` for my Socket Chat and until now It was easy to identify and was not creating any confusion but it will create big mess in future, thankfully I am using the Clean-Swift Pattern which saved me to distribute everything. 

#### Video iOS SDK
TwillioSDK 3.0.0 

#### Xcode
Xcode 11

#### iOS Version
iOS 13

**Comment by paynerc** [comment]
@hardikdevios,

Sorry for the late response. When preparing for the `3.0.0` release and the fact that we were going to be making breaking API changes, we felt that it was the proper time to audit and update the Swift APIs we were exposing.

The requirement for a three character prefix is strictly an Objective-C pattern and necessity to avoid clashes between  supplied and third party frameworks. Swift doesn't have this requirement as it implements at least a rudimentary namespacing paradigm. Having class names with a three letter prefix didn't feel very idiomatic when we were consuming the Video Framework in applications written in Swift.

The other thing we did during this process was audit how methods and delegates were being exposed in Swift and used the `NS_SWIFT_NAME` macro in places where we felt that we could provide a more Swift idiomatic implementation.

We understand that these are breaking changes to existing applications which is why we waited until a major version to make the changes.

We do recognize that some of our types have relatively generic names as you have mentioned (`VideoView` and `RemoteParticipant` for example), however If you are referring to both our implementation and yours in the same source file, we now fully support fully qualifying the types. For example you can reference `TwilioVideo.ViewView` along side your own `VideoView`.

We hope that Swift developers will find these updates beneficial to allow them to develop applications while embracing the Swift paradigms.

Let me know if you have any further concerns,

Ryan

**Comment by hardikdevios** [comment]
@paynerc Nice Explanation, Anyway mate it was just a curiosity of me behind the thought of removing the `TVI` keyword and I also think that it's better, Cheers
