### ISSUE TITLE
AudioIssueDuringCall

### ISSUE THREAD

**Issue by ManishaAstaPartners** [twilio/video-quickstart-ios#469]
###
I am Twilio for my iOS app where we use VoiceCall to send VOIP and as soon as we get connected we disconnect the audio call and connect via video call. The issue which we are facing on doing the same is most of the time while video call gets started we do not receive audio of the caller and callee. And if i try to set audio device the app gets crashed.

7 out of 10 times

**Comment by piyushtank** [comment]
@ManishaAstaPartners In order to debug this problem, can you provide following information - 

- How are you making the VoiceCall? Are you using TwilioVoice SDK and TwilioVideo SDK in the same app? 
- Can you please fill the issue template ?


> Before filing an issue please check that the issue is not already addressed by the following:
>
>  * [Video Guides](https://www.twilio.com/docs/api/video)
>  * [Changelog](https://www.twilio.com/docs/api/video/changelog-twilio-video-ios-version-2x).
> 
> If this is an issue with the QuickStart itself, file it here. If this is an issue with the SDK or how to do something with the SDK please use [twilio-video-ios](https://github.com/twilio/twilio-video-ios/issues) instead.
>
> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

### Description

[Description of the issue]

### Steps to Reproduce

1. [Step one]
2. [Step two]
3. [Insert as many steps as needed]

#### Code

```swift
// Code that helps reproduce the issue
```

#### Expected Behavior

[What you expect to happen]

#### Actual Behavior

[What actually happens]

#### Reproduces How Often

[What percentage of the time does it reproduce?]

#### Logs
Debug level logs are helpful when investigating issues. To enable debug level logging, add the following code to your application:

```.swift
TwilioVideoSDK.setLogLevel(.debug)
```

```
// Log output when the issue occurs
```

### Versions

All relevant version information for the issue.

#### Video iOS SDK

[e.g. 1.3.12 via CocoaPods]

#### Xcode

[e.g. 9.2]

#### iOS Version

[e.g. 11.2.6]

#### iOS Device

[e.g. iPhone 8 Plus]

**Comment by piyushtank** [comment]
We are tracking this issue https://github.com/twilio/twilio-video-ios/issues/85 Closing this ticket, but feel free to reopen the ticket if you think otherwise.
