### ISSUE TITLE
Broadcast extension - How to pass access tokens from the host app

### ISSUE THREAD

**Issue by SubhajeetS** [twilio/video-quickstart-ios#476]
It's a question rather than an issue.
I am using the replaykit example project to implement broadcasting(even in background).
My host app has the twilio token (my server creates it using twilio rest apis) - now how can i pass the token and room name in extension context so that my broadcast extension can connect using that token?
I am using RPSystemBroadcastPickerView as I am targeting ios >= 12

**Comment by ceaglest** [comment]
Hey @SubhajeetS,

This is a good question. It used to be possible to pass the information in the setup info for the broadcast. I am not sure how in iOS 12+ since a broadcast extension can be launched from outside of the app, or via RPSystemBroadcastPickerView.

I can investigate this further.

Best,
Chris

**Comment by SubhajeetS** [comment]
Thank you for your prompt reply.
I was wondering if there is a way to achieve screen sharing (even from background) without using RPSystemBroadcastPickerView.
My container and host app are the same. I commented the code for using RPSystemBroadcastPickerView and fallback to the default startBroadcast method - but it lets me share just the app. Screen sharing pauses when it goes to background.

**Comment by roupen** [comment]
@SubhajeetS I ended up accomplishing this with App Groups and UserDefaults. So in my broadcast extension this is the code:

```
let userDefaults = UserDefaults(suiteName: "APP_GROUP.broadcast")
        self.twilioRoomId = userDefaults?.string(forKey: "twilioRoomId")!
        self.twilioScreenToken = userDefaults?.string(forKey: "twilioScreenToken")!
```

**Comment by ceaglest** [comment]
Hey @roupen,

Thanks for the suggestion! I think NSUserDefaults would be fine for exchanging Room names but I wouldn't advise storing access tokens there because it is isn't [secure](https://github.com/nielsmouthaan/SecureNSUserDefaults).

Apps in the same [access group](https://developer.apple.com/documentation/security/keychain_services/keychain_items/sharing_access_to_keychain_items_among_a_collection_of_apps) can share items in the keychain. This might be the best way to securely exchange data between an application and an extension if you are okay with managing the lifetime of this data yourself.

Best,
Chris

**Comment by piyushtank** [comment]
Closing an old ticket but feel free to reopen or file another if you run into any issues.
