### ISSUE TITLE
Recording Local and Remote Video Frames [advice]

### ISSUE THREAD

**Issue by ksuhr1** [twilio/video-quickstart-ios#543]
### Description

I am trying to figure out the best way to record local and remote video frames for a production environment. Is this videoquickstart example based on a peer-to-peer room or small group room? I see in this link https://support.twilio.com/hc/en-us/articles/360035005493-Record-a-Video-Room-with-Twilio-Programmable-Video that you can not record in P2P room. I'd like to record audio, video, and data track and don't know if I need to set up my own database and server for this or if this can be done through Twilio. I don't want to store this data locally but in the cloud like AWS, or if Twilio has their own cloud. The recording would obviously be done with user's consent. If I enable a group room with recording, where will the recordings be stored and would I be able to play back video? Would anything need to be changed within this video quickstart example project to enable recording? Any advice would be great. Thank you.

**Comment by paynerc** [comment]
@ksuhr1,

The VideoQuickStart examples are agnostic of the room type. Being simple examples, the rooms are created Ad-hoc by the first participant that connects to a room. Take a look at the [Ad-hoc Rooms](https://www.twilio.com/docs/video/tutorials/understanding-video-rooms#ad-hoc-rooms) section of the [Understanding Video Rooms](https://www.twilio.com/docs/video/tutorials/understanding-video-rooms) guide to see how you can change the room type when creating Ad-Hoc rooms.

Developing your own recording solution is not a trivial task which is why the capability to record rooms has been added as a feature to group rooms. I would recommend taking a look at the [Understanding Video Recordings and Compositions](https://www.twilio.com/docs/video/tutorials/understanding-video-recordings-and-compositions) guide which provides a lot of information on this topic and why recordings are only offered with Group Rooms.

As far as you last question, you can easily enable recordings for the Video Quickstart without needing to make any code changes but instead changes on to the Room Topology settings for Default Rooms, as described above in the [Ad-hoc Rooms](https://www.twilio.com/docs/video/tutorials/understanding-video-rooms#ad-hoc-rooms) section of the [Understanding Video Rooms](https://www.twilio.com/docs/video/tutorials/understanding-video-rooms) guide.

Let me know if you have any further questions,

Ryan

**Comment by paynerc** [comment]
@ksuhr1,

Closing this issue, but feel free to reopen if you have any further questions.

Ryan
