### ISSUE TITLE
Using the ReplayKitExample app, but the audio of the video doesn't get delivered.

### ISSUE THREAD

**Issue by friendtree16** [twilio/video-quickstart-ios#601]
### Description

I'm sharing a video using the ReplayKitExample app, but the audio of the video doesn't get delivered.

### Steps to Reproduce
1. Open ReplayKitExample Project in Xcode.
2. Change Bundle Identifier for own ReplayKitExample , BroadcastExtention and BroadcastExtensionSetupUI.
3. Update kBroadcastExtensionBundleId and kBroadcastExtensionSetupUiBundleId for my Bundle Identifier at ViewController.swift.
4. Run ReplayKitExample on my iPhone.
5. Start broadcast.
6. Share video at file app.

#### Expected Behavior

Can hear the video sound from the web application clearly.

#### Actual Behavior

I can't hear the video sound from the web application.

#### Reproduces How Often

The recall rate is 100%.

#### Video iOS SDK

TwilioVideo 4.4

#### Xcode

XCode 12.2

#### iOS Version

14.4

#### iOS Device

iPhone 11

**Comment by ceaglest** [comment]
Hi @friendtree16,

> I can't hear the video sound from the web application.

I am sorry about this. The problem is that the example app doesn't support mixing of ReplayKit audio yet. If you only want the app audio and not the mic you can get it by changing this [line of code](https://github.com/twilio/video-quickstart-ios/blob/680cd5d8f1f2f1a081bede13205da8f903e6c642/ReplayKitExample/BroadcastExtension/SampleHandler.swift#L29).

```
    static let kAudioSampleType = RPSampleBufferType.audioApp
```

- Ref to: https://github.com/twilio/video-quickstart-ios/issues/595

Best,
Chris
